### ISSUE TITLE
How to add changelog entry without issue or PR

### ISSUE THREAD

**Issue by rawtaz** [restic/calens#1]
When there is no corresponding issue or PR for the changes you've made and want to add a changelog entry for, what's the proper way to do so (as you cannot name it `(issue|pull)-(number)`)? What should the file be named, can it be named anything?

**Comment by fd0** [comment]
Hm, excellent question. For restic, we almost always have an issue or PR before adding a change. But the file name for the changelog snipped really can be anything, `issue-1234` as well as `add-awesome-feature`, it isn't used for anything except storing the text. Since I'm not creative and lazy, I just used issue or PR IDs.

**Comment by rawtaz** [comment]
That's fine, using any filename when not having an issue or PR works for me at least. I suppose the order in which the changelog entries will be listed within each category (e.g. Sec, Enh, etc) is just alphabetical (taken from the filesystem)?

**Comment by fd0** [comment]
Yep, that's the case.

**Comment by rawtaz** [comment]
Thank you!
